### PR TITLE
rework/cleanup argument handling

### PR DESCRIPTION
**Pull request by yoshiyoshyosh**
heya

this started with a simple proposition of wanting to be able to download more than one album/label at a time, but it ended with me looking into `docopt` and realizing that a) it's pretty cool and b) there were a few bugs in how arguments were being handled with docopt here

on the bug side, docopt seems to require a format like `-d <dir> --dir <dir>` instead of `-d --dir <dir>` when defining interchangeable options that need an argument. bcdl-free was interpreting the latter as an array for values where it didn't make sense to be an array. I changed it to fix that

as for multiple albums/labels, I always found the required `-a` or `-l` argument to be weird. it's not a conventional way of handling an argument, so I decided to instead replace it with a 1-or-more required URL arguments that are simply at the end of the argument line.

detecting if a link is a label link or album/track link is pretty easy. if it contains `/album/iden` or `/track/iden`, it's the latter and use `download_album`. otherwise, it's the former and use `download_label`. if a label is being downloaded, I actually extract the label name from the `*.bandcamp.com` part of the URL and "normalize" the url to be `https://labelname.bandcamp.com/music`, since that's how you get the music grid and whatnot

let me know if anything needs to be changed or whatnot

### CODE REVIEW

**Comment by 7x11x13** [comment]
Looks good all around, a couple points:

1. Bandcamp allows labels to use a custom domain name for their Bandcamp store, so we should support domains other than `*.bandcamp.com`. I can't find one off the top of my head but I've definitely seen it before.

2. Can we preserve `-a` and `-l` options for backwards compatibility? (for now)

**Comment by yoshiyoshyosh** [comment]
> Bandcamp allows labels to use a custom domain name for their Bandcamp store, so we should support domains other than *.bandcamp.com. I can't find one off the top of my head but I've definitely seen it before.

oh duh, forgot about those since they're few and far between. here's one: https://mumbleetc.com/album/past-life

> Can we preserve -a and -l options for backwards compatibility? (for now)

yeah I was thinking about doing that, but I didn't know if we were following the `0.x` convention of "backwards compat not guaranteed". can just make them dummy options that don't do anything

**Comment by 7x11x13** [comment]
Actually it looks like they don't support custom domains anymore: https://get.bandcamp.help/hc/en-us/articles/23020691318551-How-do-I-set-up-a-custom-domain-on-Bandcamp but it would be good to handle redirects like the one you posted above

**Comment by yoshiyoshyosh** [comment]
thought this was gonna be a simple edit, but something extremely annoying has popped up...

```
$ b -f FLAC https://mumbleetc.com
INFO:httpx:HTTP Request: GET https://www.1secmail.com/api/v1/?action=getDomainList "HTTP/1.1 200 OK"
INFO:free_bandcamp_downloader:Downloading https://mumbleetc.com/album/--16
INFO:free_bandcamp_downloader:https://mumbleetc.com/album/--16 has no audio. Skipping...
INFO:free_bandcamp_downloader:Downloading https://mumbleetc.com/album/past-life
INFO:free_bandcamp_downloader:https://mumbleetc.com/album/past-life does not require email
```

that looks fine, but...

```
$ b -f FLAC https://generalmumble.bandcamp.com
INFO:httpx:HTTP Request: GET https://www.1secmail.com/api/v1/?action=getDomainList "HTTP/1.1 200 OK"
INFO:free_bandcamp_downloader:Downloading https://generalmumble.bandcamp.com/album/--16
INFO:free_bandcamp_downloader:https://generalmumble.bandcamp.com/album/--16 has no audio. Skipping...
INFO:free_bandcamp_downloader:Downloading https://generalmumble.bandcamp.com/album/past-life
Traceback (most recent call last):
  File "/home/yosh/.local/python-venv/bin/bcdl-free", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/yosh/.local/python-venv/lib/python3.12/site-packages/free_bandcamp_downloader/__main__.py", line 552, in main
    downloader.download_label(url, arguments["--force"])
  File "/home/yosh/.local/python-venv/lib/python3.12/site-packages/free_bandcamp_downloader/__main__.py", line 383, in download_label
    self.download_album(album_link, force)
  File "/home/yosh/.local/python-venv/lib/python3.12/site-packages/free_bandcamp_downloader/__main__.py", line 327, in download_album
    head_data = next(obj for obj in head_data if obj["@id"] == url)
```

trying this in a repl...

```
 >>> url
'https://generalmumble.bandcamp.com/album/past-life'
 >>> s=requests.Session()
 >>> r = s.get(url)
 >>> r
<Response [403]>
 >>> r.raise_for_status()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yosh/.local/python-venv/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://generalmumble.bandcamp.com/album/past-life
 >>> r = s.get('https://mumbleetc.com/album/past-life')
 >>> r
<Response [200]>
 >>>
```

this is also happening with 0.3.5. what gives?

trying with curl is even stranger, since it's asking us to redirect to the link that should redirect to `*.bandcamp.com`:

```
$ curl https://generalmumble.bandcamp.com/album/past-life
You are being redirected, please follow <a href="https://mumbleetc.com/album/past-life">this link to: https://mumbleetc.com/album/past-life</a>
```

meanwhile this just retrieves the page normally, not even needing a redirect:

```
$ curl 'https://mumbleetc.com/album/past-life'
```

**Comment by yoshiyoshyosh** [comment]
oh, I am a fool. the 403 in the repl was from the ciphers not being present. what's happening here is that `@id` in the `head_data` is the custom domain. that's annoying.

**Comment by yoshiyoshyosh** [comment]
seems fine from my testing.

I made `-a` and `-l` simply dummy urls that don't get parsed as arguments. custom domains and the above issue are now handled by finding the `albumRelease` object that matches the `head_data.@id`

I'm wondering about a more robust way of downloading URLs, where we can determine whether the provided link is an album or label page by seeing if there's a presence of the `head_data.@id` key, which doesn't exist for label pages. this would mean redirects to albums that don't necessarily contain `/track/` or `/album/` can be handled. this would require `download_album` and `download_label` to be reworked a bit--only near the head though. in any case, it's outside the scope of this specific PR, but what are your thoughts on it?

**Comment by 7x11x13** [comment]
> I'm wondering about a more robust way of downloading URLs, where we can determine whether the provided link is an album or label page

I think you can do this by checking the meta tag e.g. for albums it looks like: `<meta property="og:type" content="album">` and for labels looks like: `<meta property="og:type" content="band">`

**Pull request merged**
